django.request - ERROR - Internal Server Error: /dashboard/186
Traceback (most recent call last):
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/base.py", line 469, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/adityabharadwaj/Desktop/time-series-Apr10/time-series-forecasts/time-forecast-app/src/data/views.py", line 114, in dashboard_view
    return render(request, "output/dashboard.html", context)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/base.py", line 477, in parse
    raise self.error(token, e)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/base.py", line 475, in parse
    compiled_result = compile_func(self, token)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/base.py", line 477, in parse
    raise self.error(token, e)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/base.py", line 475, in parse
    compiled_result = compile_func(self, token)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/base.py", line 471, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/base.py", line 527, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 4: 'static', expected 'endblock'. Did you forget to register or load this tag?
django.request - ERROR - Internal Server Error: /dashboard/186
Traceback (most recent call last):
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/base.py", line 469, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/adityabharadwaj/Desktop/time-series-Apr10/time-series-forecasts/time-forecast-app/src/data/views.py", line 114, in dashboard_view
    return render(request, "output/dashboard.html", context)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/base.py", line 477, in parse
    raise self.error(token, e)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/base.py", line 475, in parse
    compiled_result = compile_func(self, token)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/base.py", line 477, in parse
    raise self.error(token, e)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/base.py", line 475, in parse
    compiled_result = compile_func(self, token)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/base.py", line 471, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/base.py", line 527, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 4: 'static', expected 'endblock'. Did you forget to register or load this tag?
django.request - ERROR - Internal Server Error: /dashboard/186
Traceback (most recent call last):
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/adityabharadwaj/Desktop/time-series-Apr10/time-series-forecasts/time-forecast-app/src/data/views.py", line 114, in dashboard_view
    return render(request, "output/dashboard.html", context)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/base.py", line 477, in parse
    raise self.error(token, e)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/base.py", line 475, in parse
    compiled_result = compile_func(self, token)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/base.py", line 477, in parse
    raise self.error(token, e)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/base.py", line 475, in parse
    compiled_result = compile_func(self, token)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/base.py", line 448, in parse
    raise self.error(token, e)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/base.py", line 446, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/base.py", line 562, in compile_filter
    return FilterExpression(token, self)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/base.py", line 656, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Users/adityabharadwaj/Dev/time-forecast-app/lib/python3.6/site-packages/django/template/base.py", line 568, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'crispy'
